version: "3"

services:
  db:
    image: dolthub/dolt-sql-server
    ports:
      - 3306
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d

  py-srv:
    build: py-srv
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=60
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "80:5000"
